name: Update Nodes

on:
  schedule:
    - cron: '0 */20 * * *'  # 每20小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:  # 添加必要的权限
      contents: write  # 允许写入仓库

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true  # 保存认证信息

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run node crawler
      env:
        PYTHONUNBUFFERED: 1
      run: python main.py

    - name: Check node
      run: |
        wget https://github.com/lilendian0x00/xray-knife/releases/download/v7.1.5/Xray-knife-linux-64.zip
        unzip -o Xray-knife-linux-64.zip
        chmod 777 xray-knife
        ./xray-knife http -f v2 --speedtest --sort -o result.txt -t 1000 > /dev/null
        cat result.txt

    - name: Commit changes
      run: |
        git config --local user.name 'github-actions'
        git config --local user.email 'github-actions@github.com'
        git add v2.txt
        git commit -m "Update nodes $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
        git push
